### ISSUE TITLE
Flat mode

### ISSUE THREAD

**Issue by ArnaudBarre** [rschristian/deptree#3]
Thanks for making this!

An issue I have with this is that subtree are repeated and doesn't really represent the final impact on node_modules.

I was testing it with `@eslint-react/eslint-plugin` and most sub packages of the mono repo depend on `@eslint-react/types` which makes the tree difficult to parse.

**Comment by rschristian** [comment]
Sorry, working as intended -- it's not meant to represent installed packages in `node_nodules` but the actual tree. Graphically showing repeated subtrees is largely the point, as they do continue to exist even if your file system can flatten them out a bit.

**Comment by rschristian** [comment]
In the off chance you haven't seen [npmgraph](https://npmgraph.js.org), it's what I'd recommend for a flattened view. It does it really well.
