### ISSUE TITLE
module.pkg undefined throws Cannot read properties of undefined (reading 'dependencies')

### ISSUE THREAD

**Issue by VandeurenGlenn** [rschristian/deptree#7]
have multiple varint deps, only the first one works as expected, after that all fail to find the dist-tag

![image](https://github.com/user-attachments/assets/8e4f9f0e-10f8-4847-aa95-ef54b9647ce3)

**Comment by rschristian** [comment]
> have multiple varint deps, only the first one works as expected

I have absolutely no idea what this means.

Please provide your inputs.

**Comment by VandeurenGlenn** [comment]
@rschristian 
Cannot read properties of undefined (reading 'dependencies') is thrown when I upload https://github.com/leofcoin/monorepo/blob/main/packages/chain/package.json

![image](https://github.com/user-attachments/assets/354fc24b-7c0b-4396-b334-aa02eb0fec54)

As you can see from the screenshot below it finds the correct dist-tag the first time, but after that doesn't
![image](https://private-user-images.githubusercontent.com/8685280/355934634-8e4f9f0e-10f8-4847-aa95-ef54b9647ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzU2ODEsIm5iZiI6MTcyMzEzNTM4MSwicGF0aCI6Ii84Njg1MjgwLzM1NTkzNDYzNC04ZTRmOWYwZS0xMGY4LTQ4NDctYWE5NS1lZjU0Yjk2NDdjZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTY0MzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTliMWRiZGIyZTUxYmU3Y2U0OTdjMjg1NDY2MzVjZGYxMjcxN2FhM2IzNGM5ZDE2YjI5ZmE0M2UyYTIxMTNmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LIkNQdayzeBnsMby6yBDOozKgKe8CWAHyTPA4HhKGtg)

**Comment by VandeurenGlenn** [comment]
Think I know why, the dependency is a github dependency

![image](https://github.com/user-attachments/assets/96b490da-64ac-4512-b1d1-4b331288adec)

the 'g' from github is missing

**Comment by VandeurenGlenn** [comment]
But on the other side, the created key will always be the same but yet never is a cached module used.

**Comment by rschristian** [comment]
> But on the other side, the created key will always be the same but yet never is a cached module used.

I don't know why you think this is, the cache is very clearly used. As it looks like you've inserted your own logs, they're likely set up incorrectly.

> Think I know why, the dependency is a github dependency

GitHub deps will not be supported.

**Comment by VandeurenGlenn** [comment]
@rschristian Indeed, cache works, would have been weird if it really doesn't because a simple map.

> GitHub deps will not be supported.

Oh damn, why is that? I just added initial support 
https://github.com/rschristian/deptree/compare/master...VandeurenGlenn:deptree:master

**Comment by rschristian** [comment]
Because GitHub dependencies are a _really, really_ bad idea with the current Node package managers. They are not at all equipped to use GH dependencies safely and the use should be heavily discouraged (if not removed outright).

You're referencing code that could change at any point in time without any guarantees of owner. Don't do it.

**Comment by VandeurenGlenn** [comment]
Aha, I see, makes sense!
